name: Deploy Static site to Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: 'npm'

      - name: Build and Export
        run: |
          npm run checkout
          npm run convert
          npm run drums
          npm run catalog

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./src

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5